config/routes.rb
Rails.application.routes.draw do

  root to: 'items#show'

  get 'items/show'
  get 'items', to: 'items#show'

  post 'items/search'

  get 'items/setup'
  post 'items/setup'

  post 'items/upload'

  post 'items/clear'

  post 'items/mount'

  post 'items/connect'

  post 'items/reload'

  post 'items/save'

  get 'items/regist'
  post 'items/regist'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  require 'nokogiri'
  require 'open-uri'
  require 'peddler'
  require 'amazon/ecs'
  require 'uri'
  require 'csv'

  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def show
    @user = current_user.email
    csv_data = CSV.read('app/others/csv/Flat.File.Listingloader.jp.csv', headers: true)
    gon.csv_head = csv_data
    account = Fvalue.find_by(user: current_user.email)
    if account != nil then
      res = account.list
      gon.list = account.list
    else
      gon.list = false
    end

    rt = Asin.where(user:current_user.email).pluck("rasin")
    nrt = []
    k = 0
    for p in 0..rt.length
      if rt[p] != nil then
        nrt[k]=[]
        nrt[k][0] = rt[p]
        k += 1
      end
    end

    qt = Asin.where(user:current_user.email).pluck("nasin")
    nqt = []
    k = 0
    for p in 0..qt.length
      if qt[p] != nil then
        nqt[k]=[]
        nqt[k][0] = qt[p]
        k += 1
      end
    end

    gon.regasin = nrt
    gon.ngasin = nqt

  end


  def regist
    current_email = current_user.email
    @user = current_email
    if request.post? then
      @account = Mws.new
      data = params[:MWS]
      logger.debug("\n\nDebug")
      user = Mws.find_by(User: current_email)
      if data[:AWSkey] != nil && data[:SellerId] != nil then
        if user == nil then
          Mws.create(
            User: current_user.email,
            AWSkey: data[:AWSkey],
            Skey: data[:Skey],
            SellerId:data[:SellerId]
          )
          @res1 = data[:AWSkey]
          @res2 = data[:Skey]
          @res3 = data[:SellerId]
        else
          Mws.update(
            User: current_user.email,
            AWSkey: data[:AWSkey],
            Skey: data[:Skey],
            SellerId: data[:SellerId]
          )
          @res1 = data[:AWSkey]
          @res2 = data[:Skey]
          @res3 = data[:SellerId]
        end
      else
        @res1 = data[:AWSkey]
        @res2 = data[:Skey]
        @res3 = data[:SellerId]
      end
    else
      temp = Mws.find_by(User:current_email)
      logger.debug("MWS is search!!\n\n")
      logger.debug(Mws.select("AWSkey"))
      if temp != nil then
        logger.debug("MWS is found")
        @account = Mws.find_by(User:current_email)
        @res1 = temp.AWSkey
        @res2 = temp.Skey
        @res3 = temp.SellerId
      else
        @account = Mws.new
      end
    end
  end

  def search

    body = params[:data]
    body = JSON.parse(body)

    org_url = body[0]
    pgnum = body[1]
    maxnum = body[2]
    cnum = body[3]
    input_type = body[4].to_i
    reg_asin = body[5]
    ng_asin = body[6]
    user = current_user.email
    if input_type == 1 then
      logger.debug("Case URL")
      j = 0
      data = []
      charset = nil

      url = org_url + '&page=' + pgnum.to_s
      user_agent = "Mozilla/5.0 (Windows NT 6.1; rv:28.0) Gecko/20100101 Firefox/28.0"

      begin
        html = open(url, "User-Agent" => user_agent) do |f|
          charset = f.charset
          f.read # htmlを読み込んで変数htmlに渡す
        end
      rescue OpenURI::HTTPError => error
        response = error.io
        logger.debug("\nNo." + pgnum.to_s + "\n")
        logger.debug("error!!\n")
        logger.debug(error)
      end

      doc = Nokogiri::HTML.parse(html, charset)
      doc.css('li/@data-asin').each do |list|
        cnum += 1

        if cnum > maxnum then
          break
        end
        check = "a-popover-sponsored-header-" + list.value
        if doc.xpath('//div[@id=' + check + ']')[0] == nil then
          if ng_asin.flatten.include?(list.value) == false then
            data[j] = []
            for x in 0..28
              data[j][x] = ""
            end
            data[j][0] = false
            data[j][1] = false
            data[j][9] = list.value
            data[j][14] = "⇒"
            j += 1
          end
        end
      end
    else
      j = 0
      data = []
      for j in 0..reg_asin.length - 1
        if reg_asin[j][0] == nil then
          break
        end
        data[j] = []
        for x in 0..28
          data[j][x] = ""
        end
        data[j][0] = false
        data[j][1] = false
        data[j][9] = reg_asin[j][0]
        data[j][14] = "⇒"
        j += 1
      end
    end

    #Amazonデータの取得
    account = Mws.find_by(User:user)
    if account == nil then

    end

    saws = account.AWSkey
    skey = account.Skey
    sid = account.SellerId

    client = MWS.products(
      primary_marketplace_id: "A1VC38T7YXB528",
      merchant_id: sid,
      aws_access_key_id: saws,
      aws_secret_access_key: skey
    )
    id_type = 'ASIN'
    asin = []
    asin_s = []
    requests = []
    i = 0
    j = 0
    k = 0
    m = 0
    counter = 0

    for ta in data
      asin[i] = ta[9]
      asin_s[j] = ta[9]

      prices = {
        ListingPrice: { Amount: 1000, CurrencyCode: "JPY", }
      }

      request = {
        MarketplaceId: "A1VC38T7YXB528",
        IdType: "ASIN",
        IdValue: asin[i],
        PriceToEstimateFees: prices,
        Identifier: "req" + i.to_s,
        IsAmazonFulfilled: false
      }

      requests[i] = request

      i += 1
      j += 1
      counter += 1

      if j == 5 || counter == data.length then
        logger.debug(asin_s)
        parser3 = client.get_matching_product_for_id(id_type, asin_s)
        doc3 = Nokogiri::XML(parser3.body)
        doc3.remove_namespaces!

        for tas in asin_s
          temp = doc3.xpath("//GetMatchingProductForIdResult[@Id='" + tas + "']")[0]
          title = temp.xpath('.//ItemAttributes/Title')
          if title != nil then
            title = title.text
            logger.debug(title)
          end

          image = temp.xpath('.//SmallImage/URL')
          if image != nil then
            image = image.text
            image = image.gsub('SL75','SL150')
          end

          mpn =  temp.xpath('.//ItemAttributes/PartNumber')
          if mpn != nil then
            mpn = mpn.text
          end

          if image != nil then
            data[k][2] = '<img src="' + image + '" width="80" height="60">'
          else
            data[k][2] = ""
          end
          data[k][7] = '<a href="https://amazon.co.jp/dp/' + data[k][9] + '" target="_blank">' + 'https://amazon.co.jp/dp/' + data[k][7] + '</a>'
          data[k][8] = title
          data[k][12] = mpn
          k += 1
        end
        asin_s = []
        j = 0
      end

      if i == 10 || counter == data.length then

        parser = client.get_lowest_offer_listings_for_asin(asin,{item_condition: 'Used'})
        parser1 = client.get_lowest_offer_listings_for_asin(asin,{item_condition: 'New'})
        parser2 = client.get_my_fees_estimate(requests)

        doc = Nokogiri::XML(parser.body)
        doc.remove_namespaces!

        doc1 = Nokogiri::XML(parser1.body)
        doc1.remove_namespaces!

        doc2 = Nokogiri::XML(parser2.body)
        doc2.remove_namespaces!

        for tas in asin

          temp = doc.xpath("//GetLowestOfferListingsForASINResult[@ASIN='" + tas + "']")[0]
          temp = temp.xpath(".//LandedPrice/Amount")[0]

          temp1 = doc1.xpath("//GetLowestOfferListingsForASINResult[@ASIN='" + tas + "']")[0]
          temp1 = temp1.xpath(".//LandedPrice/Amount")[0]

          fee = 0
          temp2 = doc2.xpath("//FeesEstimateResult")
          for tt in temp2
            casin = tt.xpath("FeesEstimateIdentifier/IdValue")[0].text
            if casin == tas then
              tfee = tt.xpath("FeesEstimate/FeeDetailList/FeeDetail/FeeAmount/Amount")[0]
              if tfee != nil then
                fee = tfee.text
                break
              end
            end
          end

          if temp != nil then
            lowest = temp.text
          else
            lowest = 0
          end

          if temp1 != nil then
            lowprice = temp1.text
          else
            lowprice = 0
          end

          data[m][10] = String(lowest.to_i)
          data[m][11] = String(lowprice.to_i)
          data[m][13] = String(fee.to_i/10)
          m += 1
        end

        asin = []
        i = 0
      end
    end

    render json: data
  end


  def upload
    logger.debug("\n\n\n")
    logger.debug("Debug Start!")
    current_email = current_user.email

    user= Mws.find_by(user:current_email)
    aws = user.AWSkey
    skey = user.Skey
    seller = user.SellerId

    res = params[:data]

    client = MWS.feeds(
      primary_marketplace_id: "A1VC38T7YXB528",
      merchant_id: seller,
      aws_access_key_id: aws,
      aws_secret_access_key: skey
    )

    res1 = JSON.parse(res)

    logger.debug("Pre Feed Content is \n\n")

    kk = 0
    feed_body = ""
    while kk < res1.length
      feed_body = feed_body + res1[kk].join("\t")
      feed_body = feed_body + "\n"
      kk += 1
    end

    mappings = {
      "\u{00A2}" => "\u{FFE0}",
      "\u{00A3}" => "\u{FFE1}",
      "\u{00AC}" => "\u{FFE2}",
      "\u{2016}" => "\u{2225}",
      "\u{2012}" => "\u{FF0D}",
      "\u{301C}" => "\u{FF5E}"
    }

    mappings.each{|before, after| feed_body = feed_body.gsub(before, after) }
    new_body = feed_body.encode(Encoding::Windows_31J, undef: :replace)

    logger.debug("Feed Content is \n\n")
    logger.debug(new_body)

    feed_type = "_POST_FLAT_FILE_LISTINGS_DATA_"
    parser = client.submit_feed(new_body, feed_type)
    doc = Nokogiri::XML(parser.body)

    submissionId = doc.xpath(".//mws:FeedSubmissionId", {"mws"=>"http://mws.amazonaws.com/doc/2009-01-01/"}).text
=begin
    process = ""
    err = 0
    while process != "_DONE_" do
      sleep(25)
      list = {feed_submission_id_list: submissionId}
      parser = client.get_feed_submission_list(list)
      doc = Nokogiri::XML(parser.body)
      process = doc.xpath(".//mws:FeedProcessingStatus", {"mws"=>"http://mws.amazonaws.com/doc/2009-01-01/"}).text

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/regist.html.erb
<div class="container">
  <div class="bg-success" style="align-items: center;">
    <h1 style="padding: 10px;">MWSアカウントの設定&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<small>product by <a href="http://ec-merchant.com">ec-merchant.com</a></small></h1>
  </div>
  <h4>ログイン中：<%= @user %></h4>
  <h4><%= link_to "ホーム画面", :controller => 'items', :action => 'show' %></h4>
  <p>アマゾンのMWSアカウントを登録</p>
  <%= form_tag('/items/regist') do %>
    <div class="form-group">
      <%= label :MWS, :AWSkey, 'AWSkey' %>
      <%= text_field :MWS, :AWSkey, class:'form-control', style:'width:200pt;', value:@res1 %>
    </div>
    <div class="form-group">
      <%= label :MWS, :Skey, 'Skey' %>
      <%= text_field :MWS, :Skey, class:'form-control', style:'width:200pt;', value:@res2 %>
    </div>
    <div class="form-group">
      <%= label :MWS, :SellerId, 'SellerId' %>
      <%= text_field :MWS, :SellerId, class:'form-control', style:'width:200pt;', value:@res3 %>
    </div>
    <%= submit_tag('更新', class:'btn btn-success') %>
  <% end %>

</div>

app/views/items/show.html.erb
<div class="container">
  <div class="bg-success" style="align-items: center;">
    <h1 style="padding: 10px;">Smart Sell&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h1>
  </div>
  <h4>ログイン中：<%= @user %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "MWSアカウントの設定", {:controller => "items", :action => "regist"}, {:target => "_blank"} %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "ヤフオク設定", {:controller => "items", :action => "setup"}, {:target => "_blank"} %>&nbsp;&nbsp;&nbsp;<%= link_to 'ログアウト', destroy_user_session_path, method: :get %>&nbsp;&nbsp;&nbsp;<%= link_to '管理者専用', rails_admin_path, method: :get %></h4>

  <ul class="nav nav-tabs" role="tablist">
    <li class="active" role="presentation">
      <a aria-controls="tab_a" data-toggle="tab" href="#tab_a" role="tab">1.商品情報の取得</a>
    </li>
    <li role="presentation">
      <a aria-controls="tab_b" data-toggle="tab" href="#tab_b" role="tab">2.出品CSVの作成</a>
    </li>
    <li role="presentation">
      <a aria-controls="tab_c" data-toggle="tab" href="#tab_c" role="tab">3.出品情報の設定</a>
    </li>
    <li role="presentation">
      <a aria-controls="tab_d" data-toggle="tab" href="#tab_d" role="tab">4.ASINの登録</a>
    </li>
  </ul>
  <br>
  <div class="tab-content">
    <div class="tab-pane active" id="tab_a" role="tabpanel">
      <form class="form-inline form-group">
        <div class="form-group">
          <label for="maxnumber">取得件数</label>
          <input type="number" id="maxnumber" value="9600" class="form-control" style="width: 80px;">
        </div>
        &nbsp;&nbsp;
        <div class="form-group">
          <label for="input_url">URL</label>
          <input type="text" id="input_url" class="form-control" placeholder="Input Amazon URL Here .." style="width: 140px;">
        </div>

        <div class="form-group">
          <select class="form-control" id="input_type" name="input_type">
            <option value="1" selected="selected">URL</option>
            <option value="2" >ASIN</option>
          </select>
        </div>

        <div class="form-group">
          <button id="submit_url" class="btn btn-success" type="button" style="width: 120px;">アマゾン取得</button>
        </div>
        &nbsp;

        <div class="form-group">
          <select class="form-control" id="qtype" name="number">
            <option value="1" selected="selected">型番</option>
            <option value="2" >商品名</option>
          </select>
        </div>

        <div class="form-group">
          <button id="connet_yahoo" class="btn btn-success" type="button" style="width: 120px;">ヤフオク取得</button>
        </div>
        &nbsp;
        <div class="form-group">
          <button id="reload_yahoo" class="btn btn-success" type="button" style="width: 120px;">データの更新</button>
        </div>
        &nbsp;
        <div class="form-group">
          <button id="setcsv" class="btn btn-success" type="button" style="width: 100px;">CSV作成</button>
        </div>
        &nbsp;
        <div class="form-group">
          <button id="hide" class="btn btn-success" type="button" style="width: 80px;">非表示</button>
        </div>
      </form>
      <input id="progress" value="continue" type="hidden" />
      <br>
      <div id="selected"></div>
      <div id="result"></div>
    </div>

    <div class="tab-pane" id="tab_b" role="tabpanel">
      <p>出品CSVの確認</p>
      <button id="upload" class="btn btn-success" type="button" style="width: 140px;">CSVアップロード</button>
      &nbsp;
      <% @tt=Time.now.strftime("_%Y%m%d%H%M") %>
      <a href="#" id="output" download="list<%= @tt %>.txt" class="btn btn-success" style="width: 80px;">CSV出力</a>
      <br><br>
      <div id="selected_csv"></div>
      <div id="result_csv"></div>
    </div>

    <div class="tab-pane" id="tab_c" role="tabpanel">
      <p>出品CSV作成時の詳細項目を設定</p>
      <button id="fixed_save" class="btn btn-success" type="button" style="width: 140px;">CSV設定保存</button>
      <br><br>
      <div id="fixed_csv"></div>
    </div>

    <div class="tab-pane" id="tab_d" role="tabpanel">
      <div class="row">
        <div class="col-sm-12">
          <p>ASIN設定の保存</p>
        </div>
        <div class="col-sm-2">
          <button id="set_asin_btn" class="btn btn-success" type="button" style="width: 140px;">設定保存</button>
        </div>
        <div class="col-sm-10">
          <%= form_tag('/items/clear', method: :post) do %>
             <%= submit_tag "設定のクリア", class: "btn btn-info", style: "width: 140px;" %>
          <% end %>
        </div>
        <div class="col-sm-12">
          <br>
        </div>
        <div class="col-sm-3">
          <p>情報取得したいASINを入力</p>
          <div id="set_asin"></div>
        </div>
        <div class="col-sm-3">
          <p>除外したいASINを入力</p>
          <div id="ng_asin"></div>
        </div>
      </div>
    </div>

  </div>
</div>

<%= javascript_include_tag 'items_show', 'data-turbolinks-track': 'reload'  %>